name: CI/CD Pipeline for Python Project

# Este workflow se ejecutará cuando haya un push o un pull request en la rama main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define los jobs a realizar
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout: Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Puedes ajustar la versión

      # Instalar dependencias del proyecto
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecutar pruebas
      - name: Run tests
        run: |
          pytest  # Ejecutar pruebas con pytest

  deploy:
    # El job de despliegue solo se ejecutará si el build ha pasado
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Desplegar la aplicación a Heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Debes configurar este secreto
        run: |
          heroku git:remote -a nombre_de_tu_app_heroku
          git push heroku main
